<?php 
 $GLOBALS["dictionary"]["fyn_QR_CODE_PALLETTE"]=array (
  'table' => 'fyn_qr_code_pallette',
  'audited' => true,
  'inline_edit' => true,
  'duplicate_merge' => true,
  'fields' => 
  array (
    'id' => 
    array (
      'name' => 'id',
      'vname' => 'LBL_ID',
      'type' => 'id',
      'required' => true,
      'reportable' => true,
      'comment' => 'Unique identifier',
      'inline_edit' => false,
    ),
    'name' => 
    array (
      'name' => 'name',
      'vname' => 'LBL_NAME',
      'type' => 'name',
      'link' => true,
      'dbType' => 'varchar',
      'len' => '255',
      'unified_search' => false,
      'full_text_search' => 
      array (
        'boost' => 3,
      ),
      'required' => true,
      'importable' => 'required',
      'duplicate_merge' => 'disabled',
      'merge_filter' => 'disabled',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'size' => '20',
    ),
    'date_entered' => 
    array (
      'name' => 'date_entered',
      'vname' => 'LBL_DATE_ENTERED',
      'type' => 'datetime',
      'group' => 'created_by_name',
      'comment' => 'Date record created',
      'enable_range_search' => true,
      'options' => 'date_range_search_dom',
      'inline_edit' => false,
    ),
    'date_modified' => 
    array (
      'name' => 'date_modified',
      'vname' => 'LBL_DATE_MODIFIED',
      'type' => 'datetime',
      'group' => 'modified_by_name',
      'comment' => 'Date record last modified',
      'enable_range_search' => true,
      'options' => 'date_range_search_dom',
      'inline_edit' => false,
    ),
    'modified_user_id' => 
    array (
      'name' => 'modified_user_id',
      'rname' => 'user_name',
      'id_name' => 'modified_user_id',
      'vname' => 'LBL_MODIFIED',
      'type' => 'assigned_user_name',
      'table' => 'users',
      'isnull' => 'false',
      'group' => 'modified_by_name',
      'dbType' => 'id',
      'reportable' => true,
      'comment' => 'User who last modified record',
      'massupdate' => false,
      'inline_edit' => false,
    ),
    'modified_by_name' => 
    array (
      'name' => 'modified_by_name',
      'vname' => 'LBL_MODIFIED_NAME',
      'type' => 'relate',
      'reportable' => false,
      'source' => 'non-db',
      'rname' => 'user_name',
      'table' => 'users',
      'id_name' => 'modified_user_id',
      'module' => 'Users',
      'link' => 'modified_user_link',
      'duplicate_merge' => 'disabled',
      'massupdate' => false,
      'inline_edit' => false,
    ),
    'created_by' => 
    array (
      'name' => 'created_by',
      'rname' => 'user_name',
      'id_name' => 'modified_user_id',
      'vname' => 'LBL_CREATED',
      'type' => 'assigned_user_name',
      'table' => 'users',
      'isnull' => 'false',
      'dbType' => 'id',
      'group' => 'created_by_name',
      'comment' => 'User who created record',
      'massupdate' => false,
      'inline_edit' => false,
    ),
    'created_by_name' => 
    array (
      'name' => 'created_by_name',
      'vname' => 'LBL_CREATED',
      'type' => 'relate',
      'reportable' => false,
      'link' => 'created_by_link',
      'rname' => 'user_name',
      'source' => 'non-db',
      'table' => 'users',
      'id_name' => 'created_by',
      'module' => 'Users',
      'duplicate_merge' => 'disabled',
      'importable' => 'false',
      'massupdate' => false,
      'inline_edit' => false,
    ),
    'description' => 
    array (
      'name' => 'description',
      'vname' => 'LBL_DESCRIPTION',
      'type' => 'text',
      'comment' => 'Full text of the note',
      'rows' => 6,
      'cols' => 80,
    ),
    'deleted' => 
    array (
      'name' => 'deleted',
      'vname' => 'LBL_DELETED',
      'type' => 'bool',
      'default' => '0',
      'reportable' => false,
      'comment' => 'Record deletion indicator',
    ),
    'created_by_link' => 
    array (
      'name' => 'created_by_link',
      'type' => 'link',
      'relationship' => 'fyn_qr_code_pallette_created_by',
      'vname' => 'LBL_CREATED_USER',
      'link_type' => 'one',
      'module' => 'Users',
      'bean_name' => 'User',
      'source' => 'non-db',
    ),
    'modified_user_link' => 
    array (
      'name' => 'modified_user_link',
      'type' => 'link',
      'relationship' => 'fyn_qr_code_pallette_modified_user',
      'vname' => 'LBL_MODIFIED_USER',
      'link_type' => 'one',
      'module' => 'Users',
      'bean_name' => 'User',
      'source' => 'non-db',
    ),
    'assigned_user_id' => 
    array (
      'name' => 'assigned_user_id',
      'rname' => 'user_name',
      'id_name' => 'assigned_user_id',
      'vname' => 'LBL_ASSIGNED_TO_ID',
      'group' => 'assigned_user_name',
      'type' => 'relate',
      'table' => 'users',
      'module' => 'Users',
      'reportable' => true,
      'isnull' => 'false',
      'dbType' => 'id',
      'audited' => true,
      'comment' => 'User ID assigned to record',
      'duplicate_merge' => 'disabled',
    ),
    'assigned_user_name' => 
    array (
      'name' => 'assigned_user_name',
      'link' => 'assigned_user_link',
      'vname' => 'LBL_ASSIGNED_TO_NAME',
      'rname' => 'user_name',
      'type' => 'relate',
      'reportable' => false,
      'source' => 'non-db',
      'table' => 'users',
      'id_name' => 'assigned_user_id',
      'module' => 'Users',
      'duplicate_merge' => 'disabled',
    ),
    'assigned_user_link' => 
    array (
      'name' => 'assigned_user_link',
      'type' => 'link',
      'relationship' => 'fyn_qr_code_pallette_assigned_user',
      'vname' => 'LBL_ASSIGNED_TO_USER',
      'link_type' => 'one',
      'module' => 'Users',
      'bean_name' => 'User',
      'source' => 'non-db',
      'duplicate_merge' => 'enabled',
      'rname' => 'user_name',
      'id_name' => 'assigned_user_id',
      'table' => 'users',
    ),
    'SecurityGroups' => 
    array (
      'name' => 'SecurityGroups',
      'type' => 'link',
      'relationship' => 'securitygroups_fyn_qr_code_pallette',
      'module' => 'SecurityGroups',
      'bean_name' => 'SecurityGroup',
      'source' => 'non-db',
      'vname' => 'LBL_SECURITYGROUPS',
    ),
    'total_boxes' => 
    array (
      'required' => false,
      'name' => 'total_boxes',
      'vname' => 'LBL_TOTAL_BOXES',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
    ),
    'truckinfo' => 
    array (
      'required' => false,
      'name' => 'truckinfo',
      'vname' => 'LBL_TRUCKINFO',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
    ),
    'qrimage' => 
    array (
      'required' => false,
      'name' => 'qrimage',
      'vname' => 'LBL_QRIMAGE',
      'type' => 'image',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 255,
      'size' => '20',
      'studio' => 'visible',
      'dbType' => 'varchar',
      'border' => '',
      'width' => '120',
      'height' => '',
    ),
    'status' => 
    array (
      'required' => false,
      'name' => 'status',
      'vname' => 'LBL_STATUS',
      'type' => 'enum',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'status_0',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'drivername' => 
    array (
      'required' => false,
      'name' => 'drivername',
      'vname' => 'LBL_DRIVERNAME',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
    ),
    'farmunit' => 
    array (
      'required' => false,
      'name' => 'farmunit',
      'vname' => 'LBL_FARMUNIT',
      'type' => 'enum',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'farmunit_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'class2_box_84_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Class2 Box 84',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'class2_box_84_c',
      'vname' => 'LBL_CLASS2_BOX_84',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'fyn_QR_CODE_PALLETTEclass2_box_84_c',
      'custom_module' => 'fyn_QR_CODE_PALLETTE',
    ),
    'organic_box_28_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Organic Box 28',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'organic_box_28_c',
      'vname' => 'LBL_ORGANIC_BOX_28',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'fyn_QR_CODE_PALLETTEorganic_box_28_c',
      'custom_module' => 'fyn_QR_CODE_PALLETTE',
    ),
    'class2_total_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Class2 Total',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'class2_total_c',
      'vname' => 'LBL_CLASS2_TOTAL',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'fyn_QR_CODE_PALLETTEclass2_total_c',
      'custom_module' => 'fyn_QR_CODE_PALLETTE',
    ),
    'organic_box_40_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Organic Box 40',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'organic_box_40_c',
      'vname' => 'LBL_ORGANIC_BOX_40',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'fyn_QR_CODE_PALLETTEorganic_box_40_c',
      'custom_module' => 'fyn_QR_CODE_PALLETTE',
    ),
    'organic_box_84_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Organic Box 84',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'organic_box_84_c',
      'vname' => 'LBL_ORGANIC_BOX_84',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'fyn_QR_CODE_PALLETTEorganic_box_84_c',
      'custom_module' => 'fyn_QR_CODE_PALLETTE',
    ),
    'class2_box_32_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Class2 Box 32',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'class2_box_32_c',
      'vname' => 'LBL_CLASS2_BOX_32',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'fyn_QR_CODE_PALLETTEclass2_box_32_c',
      'custom_module' => 'fyn_QR_CODE_PALLETTE',
    ),
    'organic_box_32_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Organic Box 32',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'organic_box_32_c',
      'vname' => 'LBL_ORGANIC_BOX_32',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'fyn_QR_CODE_PALLETTEorganic_box_32_c',
      'custom_module' => 'fyn_QR_CODE_PALLETTE',
    ),
    'class1_total_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Class1 Total',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'class1_total_c',
      'vname' => 'LBL_CLASS1_TOTAL',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'fyn_QR_CODE_PALLETTEclass1_total_c',
      'custom_module' => 'fyn_QR_CODE_PALLETTE',
    ),
    'class2_box_70_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Class2 Box 70',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'class2_box_70_c',
      'vname' => 'LBL_CLASS2_BOX_70',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'fyn_QR_CODE_PALLETTEclass2_box_70_c',
      'custom_module' => 'fyn_QR_CODE_PALLETTE',
    ),
    'class1_box_70_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Class1 Box 70',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'class1_box_70_c',
      'vname' => 'LBL_CLASS1_BOX_70',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'fyn_QR_CODE_PALLETTEclass1_box_70_c',
      'custom_module' => 'fyn_QR_CODE_PALLETTE',
    ),
    'organic_total_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Organic Total',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'organic_total_c',
      'vname' => 'LBL_ORGANIC_TOTAL',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'fyn_QR_CODE_PALLETTEorganic_total_c',
      'custom_module' => 'fyn_QR_CODE_PALLETTE',
    ),
    'class1_box_32_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Class1 Box 32',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'class1_box_32_c',
      'vname' => 'LBL_CLASS1_BOX_32',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'fyn_QR_CODE_PALLETTEclass1_box_32_c',
      'custom_module' => 'fyn_QR_CODE_PALLETTE',
    ),
    'class2_box_60_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Class2 Box 60',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'class2_box_60_c',
      'vname' => 'LBL_CLASS2_BOX_60',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'fyn_QR_CODE_PALLETTEclass2_box_60_c',
      'custom_module' => 'fyn_QR_CODE_PALLETTE',
    ),
    'class1_box_28_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Class1 Box 28',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'class1_box_28_c',
      'vname' => 'LBL_CLASS1_BOX_28',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'fyn_QR_CODE_PALLETTEclass1_box_28_c',
      'custom_module' => 'fyn_QR_CODE_PALLETTE',
    ),
    'fyn_qr_code_pallette_fyn_stock_in_1' => 
    array (
      'name' => 'fyn_qr_code_pallette_fyn_stock_in_1',
      'type' => 'link',
      'relationship' => 'fyn_qr_code_pallette_fyn_stock_in_1',
      'source' => 'non-db',
      'module' => 'fyn_Stock_In',
      'bean_name' => 'fyn_Stock_In',
      'side' => 'right',
      'vname' => 'LBL_FYN_QR_CODE_PALLETTE_FYN_STOCK_IN_1_FROM_FYN_STOCK_IN_TITLE',
    ),
    'fyn_qr_code_pallette_fyn_qr_code_boxes_1' => 
    array (
      'name' => 'fyn_qr_code_pallette_fyn_qr_code_boxes_1',
      'type' => 'link',
      'relationship' => 'fyn_qr_code_pallette_fyn_qr_code_boxes_1',
      'source' => 'non-db',
      'module' => 'fyn_QR_CODE_BOXES',
      'bean_name' => 'fyn_QR_CODE_BOXES',
      'side' => 'right',
      'vname' => 'LBL_FYN_QR_CODE_PALLETTE_FYN_QR_CODE_BOXES_1_FROM_FYN_QR_CODE_BOXES_TITLE',
    ),
    'organic_box_60_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Organic Box 60',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'organic_box_60_c',
      'vname' => 'LBL_ORGANIC_BOX_60',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'fyn_QR_CODE_PALLETTEorganic_box_60_c',
      'custom_module' => 'fyn_QR_CODE_PALLETTE',
    ),
    'class2_box_28_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Class2 Box 28',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'class2_box_28_c',
      'vname' => 'LBL_CLASS2_BOX_28',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'fyn_QR_CODE_PALLETTEclass2_box_28_c',
      'custom_module' => 'fyn_QR_CODE_PALLETTE',
    ),
    'class2_box_36_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Class2 Box 36',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'class2_box_36_c',
      'vname' => 'LBL_CLASS2_BOX_36',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'fyn_QR_CODE_PALLETTEclass2_box_36_c',
      'custom_module' => 'fyn_QR_CODE_PALLETTE',
    ),
    'organic_box_48_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Organic Box 48',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'organic_box_48_c',
      'vname' => 'LBL_ORGANIC_BOX_48',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'fyn_QR_CODE_PALLETTEorganic_box_48_c',
      'custom_module' => 'fyn_QR_CODE_PALLETTE',
    ),
    'class1_box_40_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Class1 Box 40',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'class1_box_40_c',
      'vname' => 'LBL_CLASS1_BOX_40',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'fyn_QR_CODE_PALLETTEclass1_box_40_c',
      'custom_module' => 'fyn_QR_CODE_PALLETTE',
    ),
    'class1_box_36_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Class1 Box 36',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'class1_box_36_c',
      'vname' => 'LBL_CLASS1_BOX_36',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'fyn_QR_CODE_PALLETTEclass1_box_36_c',
      'custom_module' => 'fyn_QR_CODE_PALLETTE',
    ),
    'product_model_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Product Model',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'product_model_c',
      'vname' => 'LBL_PRODUCT_MODEL',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'fyn_QR_CODE_PALLETTEproduct_model_c',
      'custom_module' => 'fyn_QR_CODE_PALLETTE',
    ),
    'class1_box_48_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Class1 Box 48',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'class1_box_48_c',
      'vname' => 'LBL_CLASS1_BOX_48',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'fyn_QR_CODE_PALLETTEclass1_box_48_c',
      'custom_module' => 'fyn_QR_CODE_PALLETTE',
    ),
    'class2_box_40_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Class2 Box 40',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'class2_box_40_c',
      'vname' => 'LBL_CLASS2_BOX_40',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'fyn_QR_CODE_PALLETTEclass2_box_40_c',
      'custom_module' => 'fyn_QR_CODE_PALLETTE',
    ),
    'organic_box_70_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Organic Box 70',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'organic_box_70_c',
      'vname' => 'LBL_ORGANIC_BOX_70',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'fyn_QR_CODE_PALLETTEorganic_box_70_c',
      'custom_module' => 'fyn_QR_CODE_PALLETTE',
    ),
    'class2_box_48_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Class2 Box 48',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'class2_box_48_c',
      'vname' => 'LBL_CLASS2_BOX_48',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'fyn_QR_CODE_PALLETTEclass2_box_48_c',
      'custom_module' => 'fyn_QR_CODE_PALLETTE',
    ),
    'class1_box_60_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Class1 Box 60',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'class1_box_60_c',
      'vname' => 'LBL_CLASS1_BOX_60',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'fyn_QR_CODE_PALLETTEclass1_box_60_c',
      'custom_module' => 'fyn_QR_CODE_PALLETTE',
    ),
    'no_of_boxes_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'No Of Boxes',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'no_of_boxes_c',
      'vname' => 'LBL_NO_OF_BOXES',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'fyn_QR_CODE_PALLETTEno_of_boxes_c',
      'custom_module' => 'fyn_QR_CODE_PALLETTE',
    ),
    'organic_box_36_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Organic Box 36',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'organic_box_36_c',
      'vname' => 'LBL_ORGANIC_BOX_36',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'fyn_QR_CODE_PALLETTEorganic_box_36_c',
      'custom_module' => 'fyn_QR_CODE_PALLETTE',
    ),
    'class1_box_84_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Class1 Box 84',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'class1_box_84_c',
      'vname' => 'LBL_CLASS1_BOX_84',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'fyn_QR_CODE_PALLETTEclass1_box_84_c',
      'custom_module' => 'fyn_QR_CODE_PALLETTE',
    ),
  ),
  'relationships' => 
  array (
    'fyn_qr_code_pallette_modified_user' => 
    array (
      'lhs_module' => 'Users',
      'lhs_table' => 'users',
      'lhs_key' => 'id',
      'rhs_module' => 'fyn_QR_CODE_PALLETTE',
      'rhs_table' => 'fyn_qr_code_pallette',
      'rhs_key' => 'modified_user_id',
      'relationship_type' => 'one-to-many',
    ),
    'fyn_qr_code_pallette_created_by' => 
    array (
      'lhs_module' => 'Users',
      'lhs_table' => 'users',
      'lhs_key' => 'id',
      'rhs_module' => 'fyn_QR_CODE_PALLETTE',
      'rhs_table' => 'fyn_qr_code_pallette',
      'rhs_key' => 'created_by',
      'relationship_type' => 'one-to-many',
    ),
    'fyn_qr_code_pallette_assigned_user' => 
    array (
      'lhs_module' => 'Users',
      'lhs_table' => 'users',
      'lhs_key' => 'id',
      'rhs_module' => 'fyn_QR_CODE_PALLETTE',
      'rhs_table' => 'fyn_qr_code_pallette',
      'rhs_key' => 'assigned_user_id',
      'relationship_type' => 'one-to-many',
    ),
    'securitygroups_fyn_qr_code_pallette' => 
    array (
      'lhs_module' => 'SecurityGroups',
      'lhs_table' => 'securitygroups',
      'lhs_key' => 'id',
      'rhs_module' => 'fyn_QR_CODE_PALLETTE',
      'rhs_table' => 'fyn_qr_code_pallette',
      'rhs_key' => 'id',
      'relationship_type' => 'many-to-many',
      'join_table' => 'securitygroups_records',
      'join_key_lhs' => 'securitygroup_id',
      'join_key_rhs' => 'record_id',
      'relationship_role_column' => 'module',
      'relationship_role_column_value' => 'fyn_QR_CODE_PALLETTE',
    ),
  ),
  'optimistic_locking' => true,
  'unified_search' => true,
  'indices' => 
  array (
    'id' => 
    array (
      'name' => 'fyn_qr_code_pallettepk',
      'type' => 'primary',
      'fields' => 
      array (
        0 => 'id',
      ),
    ),
  ),
  'templates' => 
  array (
    'security_groups' => 'security_groups',
    'assignable' => 'assignable',
    'basic' => 'basic',
  ),
  'custom_fields' => true,
);