<?php
  
define('sugarEntry', TRUE); 
ini_set('max_execution_time', 0);
error_reporting(E_ERROR);
ini_set('display_errors', 1);
include_once('include/entryPoint.php');
require_once("include/SugarPHPMailer.php");
require_once("modules/Administration/Administration.php");
?>

<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <title>Waypoints in Directions</title>
    <style>


        .sometext{
      display:inline;
      height: 10%;
      width:100%;
      text-align: center;
      /*padding:3%;*/
      }

      .sawtable{
      display:block;
      height: 40%;
      width:100%;
      /*padding:3%;*/
      margin-top: 25%;
      text-align: center;
      }

      .segment{
      display:block;
      height: 10%;
      width:100%;
      padding:3%;
      }
      #right-panel {
        font-family: 'Roboto','sans-serif';
        line-height: 30px;
        padding-left: 10px;
      }

      #right-panel select, #right-panel input {
        font-size: 15px;
      }

      #right-panel select {
        width: 100%;
      }

      #right-panel i {
        font-size: 12px;
      }
      html, body {
        height: 100%;
        margin: 0;
        padding: 0;
      }
      #map {
        display:inline;
        position:relative;
        height: 50%;
        float: left;
        width: 100%;
      }
      #right-panel {
        margin: 20px;
        border-width: 2px;
        width: 20%;
        height: 400px;
        float: left;
        text-align: left;
        padding-top: 0;
      }
      #directions-panel {
        height:auto;
        margin-top: 10px;
        background-color: #FFEE77;
        /*padding: 10px;*/
        /*overflow: scroll;*/
      }
    </style>    
  </head>
  <body>
        <button id="printbtn" onclick="document.getElementById('printbtn').style.display='none';window.print();">Print this page</button>
      <div class="sometext">
        <p>
            <?php
            $routebeanid=$_REQUEST['beanid'];
            $count=$_REQUEST['count'];
            $invoiceIds = $_REQUEST['selectedInvoiceIds'];
            $invoiceIdsData = explode(",",$invoiceIds);
            
             //echo "khurram<pre>";print_r($count);exit;
            $routebean = BeanFactory::getBean('fyn_routes',$routebeanid);
            $orders = $routebean->get_linked_beans('fyn_routes_aos_invoices_1','fyn_routes');
            $vlz = BeanFactory::getBean('fyn_vlzs',$routebean->fyn_vlzs_fyn_routes_1fyn_vlzs_ida);

            echo "<script> alert(dist); </script>";

            $gzone=$vlz->zone_c;$zone="";
            if($gzone=='north')
              $zone="North";
            if($gzone=='north_east')
              $zone="North East";
            if($gzone=='north_west')
              $zone="North West";
            if($gzone=='south')
              $zone="South";
            if($gzone=='south_east')
              $zone="South East";
            if($gzone=='south_west')
              $zone="South West";
            if($gzone=='ease')
              $zone="East";
            if($gzone=='west')
              $zone="West";

            // echo "shafiq<pre>";print_r($orders);exit;
            
            $i=0;
            
            ?>
            <h1 style="align:center">Tony's Avocado Delivery Route <br> Generated by : <b><u> Administrator </u></b> on <b><u> <?php echo date("d/m/Y h:i:sa"); ?> </u></b> <br> For : <?php echo $vlz->fyn_vlzs_fyn_vehicles_1_name; ?> and <?php echo $zone; ?> Zone to deliver <?php echo $count; ?> number of orders / delivery points.   </h1>
        </p>
      </div>
      <div class="map" id="map"></div>
      <div>
        
        <table class="sawtable" border="2">
          <tr>
            <th> Order ID </th>
            <th> Customer ID </th>
            <th> Customer Address </th>
            <th> Formatted Address </th>
            <th> Order Item </th>
            <th> Amount </th>
            <th> Quantity </th>
            <th> Payment Type </th>
            <th> Direction map </th>
          </tr>
          <?php
            foreach ($orders as $order) 
            {
              if(in_array($order->id, $invoiceIdsData))
              {               
             
              ?>
              <tr>
              <?php
              $o_id=$order->quote_number;
              $cust_name=$order->billing_account;
              $cust_addr=$order->shipping_address_street." ".$order->shipping_address_city." ".$order->shipping_address_state." ".$order->shipping_address_postalcode." ".$order->shipping_address_country;
              $formatted_addr=$order->formatted_address_c;
              $o_item=$order->quote_number;
              $o_amt=$order->total_amount;
               $o_qty=$order->quantity;
              $o_payment_status=$order->status;
              $o_map='https://www.google.com/maps/dir/?api=1&destination=' . $formatted_addr;

              ?>
              <td><?php echo $o_id; ?></td>
              <td><?php echo $cust_name; ?></td>
              <td><?php echo $cust_addr; ?></td>
              <td><?php echo $formatted_addr; ?></td>
              <td><?php echo $o_item; ?></td>
              <td><?php echo $o_amt; ?></td>
              <td><?php echo $o_qty; ?></td>
              <td><?php echo $o_payment_status; ?></td>
              <td ><?php echo "<a href='$o_map' color='#e62b8c'>open_in_map</a>"; ?></td>
              </tr>
              <?php
              $i++;
            }
          }
          ?>
        </table>
      </div>
      <!-- <div class="segment"> -->
      <div class="segment" id="directions-panel"></div>
      <!-- </div> -->

    <input type="submit" id="submit" style="display:none;">
    <script>

     window.onload = function(){
      document.getElementById('submit').click();
      }

      function initMap() {
        var directionsService = new google.maps.DirectionsService;
        var directionsDisplay = new google.maps.DirectionsRenderer;
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 6,
          center: {lat: 41.85, lng: -87.65}
        });
        directionsDisplay.setMap(map);

        document.getElementById('submit').addEventListener('click', function() {
          //var waypoint = <?php //echo json_encode($_REQUEST); ?>;//"<?php //print($_REQUEST); ?>";
		    	//waypoint = (Object.keys(waypoint)[0]);
			      // alert(waypoint);
			      calculateAndDisplayRoute(directionsService, directionsDisplay);
        });
      }

      function calculateAndDisplayRoute(directionsService, directionsDisplay) {
        var sawood=[];
        var waypts = [];
        // var checkboxArray = document.getElementById('waypoints'); //'Chamrajpet, JJR Nagar';
        // for (var i = 0; i < checkboxArray.length; i++) {
        //   if (checkboxArray.options[i].selected) {
        //     waypts.push({
        //       location: checkboxArray[i].value,
        //       stopover: true
        //     });
        //   }
        // }
        // sawood.push({location: "Jayanagar, Bangalore, KA", stopover: true});
        // console.log(waypts);



        // this whole thing need to be in for loop for multiple waypoint
        var waypoint = <?php echo json_encode($_REQUEST); ?>;
        waypoint = (Object.keys(waypoint)[0]);
        <?php
        foreach ($orders as $order) 
        {
          if(in_array($order->id, $invoiceIdsData))
              {  
          ?>

          waypts.push({location: "<?php echo $order->formatted_address_c; ?>", stopover: true});

          <?php
              }
        }
        ?>
        // waypts.push({location: waypoint, stopover: true});
        // above waypoint must be in for loop for multiple way points




        directionsService.route({
          origin: '13236 Paxton St, Pacoima, CA 91331',//document.getElementById('start').value, //'Bangalore, KA',
          destination:  '13236 Paxton St, Pacoima, CA 91331',//document.getElementById('end').value, //'Bangalore, KA',
          waypoints: waypts,
          optimizeWaypoints: true,
          travelMode: 'DRIVING'
        }, function(response, status) {
          if (status === 'OK') {
            directionsDisplay.setDirections(response);
            var route = response.routes[0];
            var summaryPanel = document.getElementById('directions-panel');
            var dist = "";
            summaryPanel.innerHTML = '';
            // For each route, display summary information.
            for (var i = 0; i < route.legs.length; i++) {
              var routeSegment = i + 1;
              summaryPanel.innerHTML += '<b>Route Segment: ' + routeSegment +
                  '</b><br>';
              summaryPanel.innerHTML += route.legs[i].start_address + ' to ';
              summaryPanel.innerHTML += route.legs[i].end_address + '<br>';
              summaryPanel.innerHTML += route.legs[i].distance.text + '<br><br>';
              dist += route.legs[i].distance.text+" ";
            }
            // alert(dist);
            console.log(dist);
          } else {
            window.alert('Directions request failed due to ' + status);
          }
        });
      }

    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyApkNutWzbr0PcjSGqf7qntea3mguPC8fk&callback=initMap">
    </script>
  </body>
</html>