<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for technical reasons, the Appropriate Legal Notices must
 * display the words "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '6.5.25',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => '',
  'author' => 'invoiceExport',
  'description' => 'invoiceExport',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'invoiceExport',
  'published_date' => '2019-06-21 18:56:11',
  'type' => 'module',
  'version' => 1561143381,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'invoiceExport',
  'relationships' => 
  array (
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/include/language/en_us.invoiceExport.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Invoices/language/en_us.lang.php',
      'to_module' => 'AOS_Invoices',
      'language' => 'en_us',
    ),
  ),
  'custom_fields' => 
  array (
    'AOS_Invoicesaddr_status_c' => 
    array (
      'id' => 'AOS_Invoicesaddr_status_c',
      'name' => 'addr_status_c',
      'label' => 'LBL_ADDR_STATUS_C',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'AOS_Invoices',
      'type' => 'enum',
      'max_size' => '100',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-06-16 16:29:37',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'addr_status_c_list',
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'AOS_Invoicesapproval_status_c' => 
    array (
      'id' => 'AOS_Invoicesapproval_status_c',
      'name' => 'approval_status_c',
      'label' => 'LBL_APPROVAL_STATUS',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'AOS_Invoices',
      'type' => 'enum',
      'max_size' => '100',
      'require_option' => '0',
      'default_value' => 'Processing',
      'date_modified' => '2019-06-16 16:29:37',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'approval_status_list',
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'AOS_Invoicesbalanceamount_c' => 
    array (
      'id' => 'AOS_Invoicesbalanceamount_c',
      'name' => 'balanceamount_c',
      'label' => 'LBL_BALANCEAMOUNT',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'AOS_Invoices',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-06-16 16:29:37',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'AOS_Invoicescommission_amount_c' => 
    array (
      'id' => 'AOS_Invoicescommission_amount_c',
      'name' => 'commission_amount_c',
      'label' => 'LBL_COMMISSION_AMOUNT',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'AOS_Invoices',
      'type' => 'int',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-06-16 16:29:37',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'AOS_Invoicescustomerid_c' => 
    array (
      'id' => 'AOS_Invoicescustomerid_c',
      'name' => 'customerid_c',
      'label' => 'LBL_CUSTOMERID',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'AOS_Invoices',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-06-16 16:29:37',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'AOS_Invoicesdays_overdue_c' => 
    array (
      'id' => 'AOS_Invoicesdays_overdue_c',
      'name' => 'days_overdue_c',
      'label' => 'LBL_DAYS_OVERDUE',
      'comments' => 'Days Overdue',
      'help' => 'Days Overdue',
      'module' => 'AOS_Invoices',
      'type' => 'int',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2019-06-16 16:29:37',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => NULL,
    ),
    'AOS_Invoicesdue_dates_c' => 
    array (
      'id' => 'AOS_Invoicesdue_dates_c',
      'name' => 'due_dates_c',
      'label' => 'LBL_DUE_DATES',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'AOS_Invoices',
      'type' => 'date',
      'max_size' => NULL,
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-06-16 16:29:37',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'AOS_Invoicesedited_c' => 
    array (
      'id' => 'AOS_Invoicesedited_c',
      'name' => 'edited_c',
      'label' => 'LBL_EDITED',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'AOS_Invoices',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-06-16 16:29:37',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'AOS_Invoicesflat_rate_commission_c' => 
    array (
      'id' => 'AOS_Invoicesflat_rate_commission_c',
      'name' => 'flat_rate_commission_c',
      'label' => 'LBL_FLAT_RATE_COMMISSION',
      'comments' => 'Flat Rate Commission',
      'help' => 'Flat Rate Commission',
      'module' => 'AOS_Invoices',
      'type' => 'enum',
      'max_size' => '100',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-06-16 16:29:37',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'flat_rate_commission_list',
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'AOS_Invoicesformatted_address_c' => 
    array (
      'id' => 'AOS_Invoicesformatted_address_c',
      'name' => 'formatted_address_c',
      'label' => 'LBL_FORMATTED_ADDRESS_C',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'AOS_Invoices',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-06-16 16:29:37',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'AOS_Invoicesitem10_c' => 
    array (
      'id' => 'AOS_Invoicesitem10_c',
      'name' => 'item10_c',
      'label' => 'LBL_ITEM10',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'AOS_Invoices',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-06-16 16:29:37',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'AOS_Invoicesitem11_c' => 
    array (
      'id' => 'AOS_Invoicesitem11_c',
      'name' => 'item11_c',
      'label' => 'LBL_ITEM11',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'AOS_Invoices',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-06-16 16:29:37',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'AOS_Invoicesitem12_c' => 
    array (
      'id' => 'AOS_Invoicesitem12_c',
      'name' => 'item12_c',
      'label' => 'LBL_ITEM12',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'AOS_Invoices',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-06-16 16:29:37',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'AOS_Invoicesitem13_c' => 
    array (
      'id' => 'AOS_Invoicesitem13_c',
      'name' => 'item13_c',
      'label' => 'LBL_ITEM13',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'AOS_Invoices',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-06-16 16:29:37',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'AOS_Invoicesitem14_c' => 
    array (
      'id' => 'AOS_Invoicesitem14_c',
      'name' => 'item14_c',
      'label' => 'LBL_ITEM14',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'AOS_Invoices',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-06-16 16:29:37',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'AOS_Invoicesitem15_c' => 
    array (
      'id' => 'AOS_Invoicesitem15_c',
      'name' => 'item15_c',
      'label' => 'LBL_ITEM15',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'AOS_Invoices',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-06-16 16:29:37',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'AOS_Invoicesitem1_c' => 
    array (
      'id' => 'AOS_Invoicesitem1_c',
      'name' => 'item1_c',
      'label' => 'LBL_ITEM1',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'AOS_Invoices',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-06-16 16:29:37',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'AOS_Invoicesitem2_c' => 
    array (
      'id' => 'AOS_Invoicesitem2_c',
      'name' => 'item2_c',
      'label' => 'LBL_ITEM2',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'AOS_Invoices',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-06-16 16:29:37',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'AOS_Invoicesitem3_c' => 
    array (
      'id' => 'AOS_Invoicesitem3_c',
      'name' => 'item3_c',
      'label' => 'LBL_ITEM3',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'AOS_Invoices',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-06-16 16:29:37',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'AOS_Invoicesitem4_c' => 
    array (
      'id' => 'AOS_Invoicesitem4_c',
      'name' => 'item4_c',
      'label' => 'LBL_ITEM4',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'AOS_Invoices',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-06-16 16:29:37',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'AOS_Invoicesitem5_c' => 
    array (
      'id' => 'AOS_Invoicesitem5_c',
      'name' => 'item5_c',
      'label' => 'LBL_ITEM5',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'AOS_Invoices',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-06-16 16:29:37',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'AOS_Invoicesitem6_c' => 
    array (
      'id' => 'AOS_Invoicesitem6_c',
      'name' => 'item6_c',
      'label' => 'LBL_ITEM6',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'AOS_Invoices',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-06-16 16:29:37',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'AOS_Invoicesitem7_c' => 
    array (
      'id' => 'AOS_Invoicesitem7_c',
      'name' => 'item7_c',
      'label' => 'LBL_ITEM7',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'AOS_Invoices',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-06-16 16:29:37',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'AOS_Invoicesitem8_c' => 
    array (
      'id' => 'AOS_Invoicesitem8_c',
      'name' => 'item8_c',
      'label' => 'LBL_ITEM8',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'AOS_Invoices',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-06-16 16:29:37',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'AOS_Invoicesitem9_c' => 
    array (
      'id' => 'AOS_Invoicesitem9_c',
      'name' => 'item9_c',
      'label' => 'LBL_ITEM9',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'AOS_Invoices',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-06-16 16:29:37',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'AOS_Invoicesorderid_c' => 
    array (
      'id' => 'AOS_Invoicesorderid_c',
      'name' => 'orderid_c',
      'label' => 'LBL_ORDERID',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'AOS_Invoices',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-06-16 16:29:37',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'AOS_Invoicespercentage_commission_c' => 
    array (
      'id' => 'AOS_Invoicespercentage_commission_c',
      'name' => 'percentage_commission_c',
      'label' => 'LBL_PERCENTAGE_COMMISSION',
      'comments' => 'Percentage Commission',
      'help' => 'Percentage Commission',
      'module' => 'AOS_Invoices',
      'type' => 'enum',
      'max_size' => '100',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-06-16 16:29:37',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'percentage_commission_list',
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'AOS_Invoicessales_commission_user_c' => 
    array (
      'id' => 'AOS_Invoicessales_commission_user_c',
      'name' => 'sales_commission_user_c',
      'label' => 'LBL_SALES_COMMISSION_USER',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'AOS_Invoices',
      'type' => 'relate',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-06-16 16:29:37',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => 'Users',
      'ext3' => 'user_id_c',
      'ext4' => NULL,
    ),
    'AOS_Invoicestotal_commission_amount_c' => 
    array (
      'id' => 'AOS_Invoicestotal_commission_amount_c',
      'name' => 'total_commission_amount_c',
      'label' => 'LBL_TOTAL_COMMISSION_AMOUNT',
      'comments' => 'Total Commission Amount',
      'help' => 'Total Commission Amount',
      'module' => 'AOS_Invoices',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-06-16 16:29:37',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'AOS_Invoicesuser_id_c' => 
    array (
      'id' => 'AOS_Invoicesuser_id_c',
      'name' => 'user_id_c',
      'label' => 'LBL_SALES_COMMISSION_USER_USER_ID',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'AOS_Invoices',
      'type' => 'id',
      'max_size' => '36',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-06-16 16:29:37',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
  ),
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Invoices/metadata/SearchFields.php',
      'to' => 'custom/modules/AOS_Invoices/metadata/SearchFields.php',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Invoices/metadata/SearchFields.php',
      'to' => 'custom/working/modules/AOS_Invoices/metadata/SearchFields.php',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Invoices/metadata/dashletviewdefs.php',
      'to' => 'custom/modules/AOS_Invoices/metadata/dashletviewdefs.php',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Invoices/metadata/dashletviewdefs.php',
      'to' => 'custom/working/modules/AOS_Invoices/metadata/dashletviewdefs.php',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Invoices/metadata/detailviewdefs.php',
      'to' => 'custom/modules/AOS_Invoices/metadata/detailviewdefs.php',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Invoices/metadata/detailviewdefs.php',
      'to' => 'custom/working/modules/AOS_Invoices/metadata/detailviewdefs.php',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Invoices/metadata/editviewdefs.php',
      'to' => 'custom/modules/AOS_Invoices/metadata/editviewdefs.php',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Invoices/metadata/editviewdefs.php',
      'to' => 'custom/working/modules/AOS_Invoices/metadata/editviewdefs.php',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Invoices/metadata/listviewdefs.php',
      'to' => 'custom/modules/AOS_Invoices/metadata/listviewdefs.php',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Invoices/metadata/popupdefs.php',
      'to' => 'custom/modules/AOS_Invoices/metadata/popupdefs.php',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Invoices/metadata/popupdefs.php',
      'to' => 'custom/working/modules/AOS_Invoices/metadata/popupdefs.php',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Invoices/metadata/quickcreatedefs.php',
      'to' => 'custom/modules/AOS_Invoices/metadata/quickcreatedefs.php',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Invoices/metadata/quickcreatedefs.php',
      'to' => 'custom/working/modules/AOS_Invoices/metadata/quickcreatedefs.php',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Invoices/metadata/searchdefs.php',
      'to' => 'custom/modules/AOS_Invoices/metadata/searchdefs.php',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Invoices/metadata/searchdefs.php',
      'to' => 'custom/working/modules/AOS_Invoices/metadata/searchdefs.php',
    ),
    15 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\AOS_Invoices\\Ext\\Language\\en_us.change_invoice_status_label.php',
      'to' => 'custom\\Extension\\modules\\AOS_Invoices\\Ext\\Language\\en_us.change_invoice_status_label.php',
    ),
    16 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\AOS_Invoices\\Ext\\Language\\en_us.CustomCode_19_May-2019.php',
      'to' => 'custom\\Extension\\modules\\AOS_Invoices\\Ext\\Language\\en_us.CustomCode_19_May-2019.php',
    ),
    17 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\AOS_Invoices\\Ext\\Language\\en_us.dotonlocal.php',
      'to' => 'custom\\Extension\\modules\\AOS_Invoices\\Ext\\Language\\en_us.dotonlocal.php',
    ),
    18 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\AOS_Invoices\\Ext\\Language\\en_us.FieldsScreen.php',
      'to' => 'custom\\Extension\\modules\\AOS_Invoices\\Ext\\Language\\en_us.FieldsScreen.php',
    ),
    19 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\AOS_Invoices\\Ext\\Language\\en_us.lablechangeforinvoice.php',
      'to' => 'custom\\Extension\\modules\\AOS_Invoices\\Ext\\Language\\en_us.lablechangeforinvoice.php',
    ),
    20 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\AOS_Invoices\\Ext\\Language\\en_us.servertolocalnew.php',
      'to' => 'custom\\Extension\\modules\\AOS_Invoices\\Ext\\Language\\en_us.servertolocalnew.php',
    ),
    21 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_addr_status_c.php',
      'to' => 'custom\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_addr_status_c.php',
    ),
    22 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_approval_status_c.php',
      'to' => 'custom\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_approval_status_c.php',
    ),
    23 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_balanceamount_c.php',
      'to' => 'custom\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_balanceamount_c.php',
    ),
    24 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_billing_account.php',
      'to' => 'custom\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_billing_account.php',
    ),
    25 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_commission_amount_c.php',
      'to' => 'custom\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_commission_amount_c.php',
    ),
    26 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_customerid_c.php',
      'to' => 'custom\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_customerid_c.php',
    ),
    27 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_days_overdue_c.php',
      'to' => 'custom\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_days_overdue_c.php',
    ),
    28 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_due_date.php',
      'to' => 'custom\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_due_date.php',
    ),
    29 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_due_dates_c.php',
      'to' => 'custom\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_due_dates_c.php',
    ),
    30 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_edited_c.php',
      'to' => 'custom\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_edited_c.php',
    ),
    31 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_flat_rate_commission_c.php',
      'to' => 'custom\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_flat_rate_commission_c.php',
    ),
    32 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_formatted_address_c.php',
      'to' => 'custom\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_formatted_address_c.php',
    ),
    33 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_item10_c.php',
      'to' => 'custom\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_item10_c.php',
    ),
    34 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_item11_c.php',
      'to' => 'custom\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_item11_c.php',
    ),
    35 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_item12_c.php',
      'to' => 'custom\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_item12_c.php',
    ),
    36 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_item13_c.php',
      'to' => 'custom\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_item13_c.php',
    ),
    37 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_item14_c.php',
      'to' => 'custom\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_item14_c.php',
    ),
    38 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_item15_c.php',
      'to' => 'custom\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_item15_c.php',
    ),
    39 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_item1_c.php',
      'to' => 'custom\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_item1_c.php',
    ),
    40 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_item2_c.php',
      'to' => 'custom\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_item2_c.php',
    ),
    41 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_item3_c.php',
      'to' => 'custom\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_item3_c.php',
    ),
    42 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_item4_c.php',
      'to' => 'custom\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_item4_c.php',
    ),
    43 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_item5_c.php',
      'to' => 'custom\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_item5_c.php',
    ),
    44 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_item6_c.php',
      'to' => 'custom\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_item6_c.php',
    ),
    45 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_item7_c.php',
      'to' => 'custom\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_item7_c.php',
    ),
    46 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_item8_c.php',
      'to' => 'custom\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_item8_c.php',
    ),
    47 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_item9_c.php',
      'to' => 'custom\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_item9_c.php',
    ),
    48 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_orderid_c.php',
      'to' => 'custom\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_orderid_c.php',
    ),
    49 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_percentage_commission_c.php',
      'to' => 'custom\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_percentage_commission_c.php',
    ),
    50 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_sales_commission_user_c.php',
      'to' => 'custom\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_sales_commission_user_c.php',
    ),
    51 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_status.php',
      'to' => 'custom\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_status.php',
    ),
    52 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_total_commission_amount_c.php',
      'to' => 'custom\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_total_commission_amount_c.php',
    ),
    53 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_user_id_c.php',
      'to' => 'custom\\Extension\\modules\\AOS_Invoices\\Ext\\Vardefs\\sugarfield_user_id_c.php',
    ),
  ),
);