<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for technical reasons, the Appropriate Legal Notices must
 * display the words "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '6.5.25',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => '',
  'author' => 'stockIn',
  'description' => 'stockIn',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'stockIn',
  'published_date' => '2019-06-28 17:12:00',
  'type' => 'module',
  'version' => 1561741925,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'stockIn',
  'relationships' => 
  array (
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/include/language/en_us.stockIn.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/fyn_Stock_In/language/en_us.lang.php',
      'to_module' => 'fyn_Stock_In',
      'language' => 'en_us',
    ),
  ),
  'custom_fields' => 
  array (
    'fyn_Stock_Indo_not_delete_c' => 
    array (
      'id' => 'fyn_Stock_Indo_not_delete_c',
      'name' => 'do_not_delete_c',
      'label' => 'LBL_DO_NOT_DELETE',
      'comments' => '',
      'help' => '',
      'module' => 'fyn_Stock_In',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-11-20 14:13:02',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'fyn_Stock_Infrom1_c' => 
    array (
      'id' => 'fyn_Stock_Infrom1_c',
      'name' => 'from1_c',
      'label' => 'LBL_FROM1',
      'comments' => '',
      'help' => '',
      'module' => 'fyn_Stock_In',
      'type' => 'enum',
      'max_size' => '100',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-11-30 07:46:37',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'from1_list',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'fyn_Stock_Infyn_vehicle_id_c' => 
    array (
      'id' => 'fyn_Stock_Infyn_vehicle_id_c',
      'name' => 'fyn_vehicle_id_c',
      'label' => 'LBL_SELECTVEHICLE_FYN_VEHICLE_ID',
      'comments' => '',
      'help' => '',
      'module' => 'fyn_Stock_In',
      'type' => 'id',
      'max_size' => '36',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2018-11-30 07:51:06',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'fyn_Stock_Inselectvehicle_c' => 
    array (
      'id' => 'fyn_Stock_Inselectvehicle_c',
      'name' => 'selectvehicle_c',
      'label' => 'LBL_SELECTVEHICLE',
      'comments' => '',
      'help' => '',
      'module' => 'fyn_Stock_In',
      'type' => 'relate',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2018-11-30 07:51:06',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => 'fyn_Vehicle',
      'ext3' => 'fyn_vehicle_id_c',
      'ext4' => '',
    ),
    'fyn_Stock_Instatus_c' => 
    array (
      'id' => 'fyn_Stock_Instatus_c',
      'name' => 'status_c',
      'label' => 'LBL_STATUS',
      'comments' => 'Status',
      'help' => 'Status',
      'module' => 'fyn_Stock_In',
      'type' => 'enum',
      'max_size' => '100',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-05-26 17:38:18',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'status_list',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'fyn_Stock_Invender_c' => 
    array (
      'id' => 'fyn_Stock_Invender_c',
      'name' => 'vender_c',
      'label' => 'LBL_VENDER',
      'comments' => 'Vender',
      'help' => 'Vender',
      'module' => 'fyn_Stock_In',
      'type' => 'enum',
      'max_size' => '100',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-05-26 17:18:06',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'vender_list',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
  ),
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/fyn_Stock_In/metadata/SearchFields.php',
      'to' => 'custom/modules/fyn_Stock_In/metadata/SearchFields.php',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/fyn_Stock_In/metadata/SearchFields.php',
      'to' => 'custom/working/modules/fyn_Stock_In/metadata/SearchFields.php',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/fyn_Stock_In/metadata/detailviewdefs.php',
      'to' => 'custom/modules/fyn_Stock_In/metadata/detailviewdefs.php',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/modules/fyn_Stock_In/metadata/detailviewdefs.php',
      'to' => 'custom/working/modules/fyn_Stock_In/metadata/detailviewdefs.php',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/modules/fyn_Stock_In/metadata/editviewdefs.php',
      'to' => 'custom/modules/fyn_Stock_In/metadata/editviewdefs.php',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/modules/fyn_Stock_In/metadata/editviewdefs.php',
      'to' => 'custom/working/modules/fyn_Stock_In/metadata/editviewdefs.php',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/modules/fyn_Stock_In/metadata/listviewdefs.php',
      'to' => 'custom/modules/fyn_Stock_In/metadata/listviewdefs.php',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/modules/fyn_Stock_In/metadata/quickcreatedefs.php',
      'to' => 'custom/modules/fyn_Stock_In/metadata/quickcreatedefs.php',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/modules/fyn_Stock_In/metadata/quickcreatedefs.php',
      'to' => 'custom/working/modules/fyn_Stock_In/metadata/quickcreatedefs.php',
    ),
    9 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\fyn_Stock_In\\Ext\\Vardefs\\sugarfield_date_entered.php',
      'to' => 'custom\\Extension\\modules\\fyn_Stock_In\\Ext\\Vardefs\\sugarfield_date_entered.php',
    ),
    10 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\fyn_Stock_In\\Ext\\Vardefs\\sugarfield_do_not_delete_c.php',
      'to' => 'custom\\Extension\\modules\\fyn_Stock_In\\Ext\\Vardefs\\sugarfield_do_not_delete_c.php',
    ),
    11 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\fyn_Stock_In\\Ext\\Vardefs\\sugarfield_from1_c.php',
      'to' => 'custom\\Extension\\modules\\fyn_Stock_In\\Ext\\Vardefs\\sugarfield_from1_c.php',
    ),
    12 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\fyn_Stock_In\\Ext\\Vardefs\\sugarfield_fyn_vehicle_id_c.php',
      'to' => 'custom\\Extension\\modules\\fyn_Stock_In\\Ext\\Vardefs\\sugarfield_fyn_vehicle_id_c.php',
    ),
    13 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\fyn_Stock_In\\Ext\\Vardefs\\sugarfield_name.php',
      'to' => 'custom\\Extension\\modules\\fyn_Stock_In\\Ext\\Vardefs\\sugarfield_name.php',
    ),
    14 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\fyn_Stock_In\\Ext\\Vardefs\\sugarfield_quantity.php',
      'to' => 'custom\\Extension\\modules\\fyn_Stock_In\\Ext\\Vardefs\\sugarfield_quantity.php',
    ),
    15 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\fyn_Stock_In\\Ext\\Vardefs\\sugarfield_selectvehicle_c.php',
      'to' => 'custom\\Extension\\modules\\fyn_Stock_In\\Ext\\Vardefs\\sugarfield_selectvehicle_c.php',
    ),
    16 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\fyn_Stock_In\\Ext\\Vardefs\\sugarfield_status_c.php',
      'to' => 'custom\\Extension\\modules\\fyn_Stock_In\\Ext\\Vardefs\\sugarfield_status_c.php',
    ),
    17 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\fyn_Stock_In\\Ext\\Vardefs\\sugarfield_vender_c.php',
      'to' => 'custom\\Extension\\modules\\fyn_Stock_In\\Ext\\Vardefs\\sugarfield_vender_c.php',
    ),
  ),
);