<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for technical reasons, the Appropriate Legal Notices must
 * display the words "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '6.5.25',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => '',
  'author' => 'user_studio',
  'description' => 'user_studio',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'user_studio',
  'published_date' => '2019-07-07 16:33:46',
  'type' => 'module',
  'version' => 1562517251,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'user_studio',
  'relationships' => 
  array (
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/include/language/en_us.user_studio.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Users/language/en_us.lang.php',
      'to_module' => 'Users',
      'language' => 'en_us',
    ),
  ),
  'custom_fields' => 
  array (
    'Userscommision_rate_c' => 
    array (
      'id' => 'Userscommision_rate_c',
      'name' => 'commision_rate_c',
      'label' => 'LBL_COMMISION_RATE',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'Users',
      'type' => 'int',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-06-16 16:29:37',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'Usersflat_rate_commission_c' => 
    array (
      'id' => 'Usersflat_rate_commission_c',
      'name' => 'flat_rate_commission_c',
      'label' => 'LBL_FLAT_RATE_COMMISSION',
      'comments' => 'Flat Rate Commission',
      'help' => 'Flat Rate Commission',
      'module' => 'Users',
      'type' => 'enum',
      'max_size' => '100',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-06-16 16:29:37',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'flat_rate_commission_list',
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'Userspercentage_commission_c' => 
    array (
      'id' => 'Userspercentage_commission_c',
      'name' => 'percentage_commission_c',
      'label' => 'LBL_PERCENTAGE_COMMISSION',
      'comments' => 'Percentage Commission',
      'help' => 'Percentage Commission',
      'module' => 'Users',
      'type' => 'enum',
      'max_size' => '100',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-06-16 16:29:37',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'percentage_commission_list',
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'Usersuser_role_c' => 
    array (
      'id' => 'Usersuser_role_c',
      'name' => 'user_role_c',
      'label' => 'LBL_USER_ROLE',
      'comments' => 'User Role',
      'help' => 'User Role',
      'module' => 'Users',
      'type' => 'enum',
      'max_size' => '100',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2019-07-06 11:48:07',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'user_role_list',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
  ),
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Users/metadata/SearchFields.php',
      'to' => 'custom/modules/Users/metadata/SearchFields.php',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Users/metadata/SearchFields.php',
      'to' => 'custom/working/modules/Users/metadata/SearchFields.php',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Users/metadata/detailviewdefs.php',
      'to' => 'custom/modules/Users/metadata/detailviewdefs.php',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Users/metadata/detailviewdefs.php',
      'to' => 'custom/working/modules/Users/metadata/detailviewdefs.php',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Users/metadata/editviewdefs.php',
      'to' => 'custom/modules/Users/metadata/editviewdefs.php',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Users/metadata/editviewdefs.php',
      'to' => 'custom/working/modules/Users/metadata/editviewdefs.php',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Users/metadata/popupdefs.php',
      'to' => 'custom/modules/Users/metadata/popupdefs.php',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Users/metadata/popupdefs.php',
      'to' => 'custom/working/modules/Users/metadata/popupdefs.php',
    ),
    8 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\Users\\Ext\\Language\\en_us.dotonlocal.php',
      'to' => 'custom\\Extension\\modules\\Users\\Ext\\Language\\en_us.dotonlocal.php',
    ),
    9 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\Users\\Ext\\Language\\en_us.servertolocalnew.php',
      'to' => 'custom\\Extension\\modules\\Users\\Ext\\Language\\en_us.servertolocalnew.php',
    ),
    10 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\Users\\Ext\\Vardefs\\sugarfield_commision_rate_c.php',
      'to' => 'custom\\Extension\\modules\\Users\\Ext\\Vardefs\\sugarfield_commision_rate_c.php',
    ),
    11 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\Users\\Ext\\Vardefs\\sugarfield_flat_rate_commission_c.php',
      'to' => 'custom\\Extension\\modules\\Users\\Ext\\Vardefs\\sugarfield_flat_rate_commission_c.php',
    ),
    12 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\Users\\Ext\\Vardefs\\sugarfield_percentage_commission_c.php',
      'to' => 'custom\\Extension\\modules\\Users\\Ext\\Vardefs\\sugarfield_percentage_commission_c.php',
    ),
    13 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\Users\\Ext\\Vardefs\\sugarfield_user_role_c.php',
      'to' => 'custom\\Extension\\modules\\Users\\Ext\\Vardefs\\sugarfield_user_role_c.php',
    ),
  ),
);