<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2017 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for  technical reasons, the Appropriate Legal Notices must
 * display the words  "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */



// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '6.5.25',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => '',
  'author' => 'Fynsis',
  'description' => '',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'Qr_code',
  'published_date' => '2018-11-21 01:21:55',
  'type' => 'module',
  'version' => 1542763315,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'Qr_code',
  'relationships' => 
  array (
    0 => 
    array (
      'meta_data' => '<basepath>/metadata/qr_qr_pallete_qr_qr_boxes_1MetaData.php',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/include/language/en_us.Qr_code.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/qr_QR_Boxes/language/en_us.lang.php',
      'to_module' => 'qr_QR_Boxes',
      'language' => 'en_us',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/qr_QR_Pallete/language/en_us.lang.php',
      'to_module' => 'qr_QR_Pallete',
      'language' => 'en_us',
    ),
  ),
  'custom_fields' => 
  array (
    'qr_QR_Boxesno_of_boxes_c' => 
    array (
      'id' => 'qr_QR_Boxesno_of_boxes_c',
      'name' => 'no_of_boxes_c',
      'label' => 'LBL_NO_OF_BOXES',
      'comments' => '',
      'help' => '',
      'module' => 'qr_QR_Boxes',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-08-23 08:55:43',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'qr_QR_Boxesproduct_category_c' => 
    array (
      'id' => 'qr_QR_Boxesproduct_category_c',
      'name' => 'product_category_c',
      'label' => 'LBL_PRODUCT_CATEGORY',
      'comments' => '',
      'help' => '',
      'module' => 'qr_QR_Boxes',
      'type' => 'enum',
      'max_size' => '100',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2018-08-23 08:27:13',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'product_category_list',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'qr_QR_Boxesproduct_name_c' => 
    array (
      'id' => 'qr_QR_Boxesproduct_name_c',
      'name' => 'product_name_c',
      'label' => 'LBL_PRODUCT_NAME',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'qr_QR_Boxes',
      'type' => 'enum',
      'max_size' => '100',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2018-08-23 08:53:52',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'product_name_list',
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'qr_QR_Boxesqr_boxes_id_c' => 
    array (
      'id' => 'qr_QR_Boxesqr_boxes_id_c',
      'name' => 'qr_boxes_id_c',
      'label' => 'LBL_QR_BOXES_ID',
      'comments' => '',
      'help' => '',
      'module' => 'qr_QR_Boxes',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-08-23 08:58:41',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'qr_QR_Boxesqr_image_c' => 
    array (
      'id' => 'qr_QR_Boxesqr_image_c',
      'name' => 'qr_image_c',
      'label' => 'LBL_QR_IMAGE',
      'comments' => '',
      'help' => '',
      'module' => 'qr_QR_Boxes',
      'type' => 'image',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2018-08-24 07:09:42',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '120',
      'ext3' => '',
      'ext4' => '',
    ),
    'qr_QR_Boxestruck_info_c' => 
    array (
      'id' => 'qr_QR_Boxestruck_info_c',
      'name' => 'truck_info_c',
      'label' => 'LBL_TRUCK_INFO',
      'comments' => '',
      'help' => '',
      'module' => 'qr_QR_Boxes',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-10-30 17:06:09',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'qr_QR_Palleteclass1_box_28_c' => 
    array (
      'id' => 'qr_QR_Palleteclass1_box_28_c',
      'name' => 'class1_box_28_c',
      'label' => 'LBL_CLASS1_BOX_28_C',
      'comments' => '',
      'help' => '',
      'module' => 'qr_QR_Pallete',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-08-23 07:15:31',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'qr_QR_Palleteclass1_box_32_c' => 
    array (
      'id' => 'qr_QR_Palleteclass1_box_32_c',
      'name' => 'class1_box_32_c',
      'label' => 'LBL_CLASS1_BOX_32',
      'comments' => '',
      'help' => '',
      'module' => 'qr_QR_Pallete',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-08-23 06:21:12',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'qr_QR_Palleteclass1_box_36_c' => 
    array (
      'id' => 'qr_QR_Palleteclass1_box_36_c',
      'name' => 'class1_box_36_c',
      'label' => 'LBL_CLASS1_BOX_36',
      'comments' => '',
      'help' => '',
      'module' => 'qr_QR_Pallete',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-08-23 06:22:16',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'qr_QR_Palleteclass1_box_40_c' => 
    array (
      'id' => 'qr_QR_Palleteclass1_box_40_c',
      'name' => 'class1_box_40_c',
      'label' => 'LBL_CLASS1_BOX_40',
      'comments' => '',
      'help' => '',
      'module' => 'qr_QR_Pallete',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-08-23 06:22:32',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'qr_QR_Palleteclass1_box_48_c' => 
    array (
      'id' => 'qr_QR_Palleteclass1_box_48_c',
      'name' => 'class1_box_48_c',
      'label' => 'LBL_CLASS1_BOX_48',
      'comments' => '',
      'help' => '',
      'module' => 'qr_QR_Pallete',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-08-23 06:23:07',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'qr_QR_Palleteclass1_box_60_c' => 
    array (
      'id' => 'qr_QR_Palleteclass1_box_60_c',
      'name' => 'class1_box_60_c',
      'label' => 'LBL_CLASS1_BOX_60',
      'comments' => '',
      'help' => '',
      'module' => 'qr_QR_Pallete',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-08-23 06:23:29',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'qr_QR_Palleteclass1_box_70_c' => 
    array (
      'id' => 'qr_QR_Palleteclass1_box_70_c',
      'name' => 'class1_box_70_c',
      'label' => 'LBL_CLASS1_BOX_70',
      'comments' => '',
      'help' => '',
      'module' => 'qr_QR_Pallete',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-08-23 06:23:53',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'qr_QR_Palleteclass1_box_84_c' => 
    array (
      'id' => 'qr_QR_Palleteclass1_box_84_c',
      'name' => 'class1_box_84_c',
      'label' => 'LBL_CLASS1_BOX_84',
      'comments' => '',
      'help' => '',
      'module' => 'qr_QR_Pallete',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-08-23 06:24:23',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'qr_QR_Palleteclass1_total_c' => 
    array (
      'id' => 'qr_QR_Palleteclass1_total_c',
      'name' => 'class1_total_c',
      'label' => 'LBL_CLASS1_TOTAL',
      'comments' => '',
      'help' => '',
      'module' => 'qr_QR_Pallete',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-08-23 07:44:19',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'qr_QR_Palleteclass2_box_28_c' => 
    array (
      'id' => 'qr_QR_Palleteclass2_box_28_c',
      'name' => 'class2_box_28_c',
      'label' => 'LBL_CLASS2_BOX_28',
      'comments' => '',
      'help' => '',
      'module' => 'qr_QR_Pallete',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-08-23 06:25:39',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'qr_QR_Palleteclass2_box_32_c' => 
    array (
      'id' => 'qr_QR_Palleteclass2_box_32_c',
      'name' => 'class2_box_32_c',
      'label' => 'LBL_CLASS2_BOX_32',
      'comments' => '',
      'help' => '',
      'module' => 'qr_QR_Pallete',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-08-23 06:25:56',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'qr_QR_Palleteclass2_box_36_c' => 
    array (
      'id' => 'qr_QR_Palleteclass2_box_36_c',
      'name' => 'class2_box_36_c',
      'label' => 'LBL_CLASS2_BOX_36',
      'comments' => '',
      'help' => '',
      'module' => 'qr_QR_Pallete',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-08-23 06:26:10',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'qr_QR_Palleteclass2_box_40_c' => 
    array (
      'id' => 'qr_QR_Palleteclass2_box_40_c',
      'name' => 'class2_box_40_c',
      'label' => 'LBL_CLASS2_BOX_40',
      'comments' => '',
      'help' => '',
      'module' => 'qr_QR_Pallete',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-08-23 06:26:34',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'qr_QR_Palleteclass2_box_48_c' => 
    array (
      'id' => 'qr_QR_Palleteclass2_box_48_c',
      'name' => 'class2_box_48_c',
      'label' => 'LBL_CLASS2_BOX_48',
      'comments' => '',
      'help' => '',
      'module' => 'qr_QR_Pallete',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-08-23 06:27:10',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'qr_QR_Palleteclass2_box_60_c' => 
    array (
      'id' => 'qr_QR_Palleteclass2_box_60_c',
      'name' => 'class2_box_60_c',
      'label' => 'LBL_CLASS2_BOX_60',
      'comments' => '',
      'help' => '',
      'module' => 'qr_QR_Pallete',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-08-23 06:27:22',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'qr_QR_Palleteclass2_box_70_c' => 
    array (
      'id' => 'qr_QR_Palleteclass2_box_70_c',
      'name' => 'class2_box_70_c',
      'label' => 'LBL_CLASS2_BOX_70',
      'comments' => '',
      'help' => '',
      'module' => 'qr_QR_Pallete',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-08-23 06:27:47',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'qr_QR_Palleteclass2_box_84_c' => 
    array (
      'id' => 'qr_QR_Palleteclass2_box_84_c',
      'name' => 'class2_box_84_c',
      'label' => 'LBL_CLASS2_BOX_84',
      'comments' => '',
      'help' => '',
      'module' => 'qr_QR_Pallete',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-08-23 06:28:44',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'qr_QR_Palleteclass2_total_c' => 
    array (
      'id' => 'qr_QR_Palleteclass2_total_c',
      'name' => 'class2_total_c',
      'label' => 'LBL_CLASS2_TOTAL',
      'comments' => '',
      'help' => '',
      'module' => 'qr_QR_Pallete',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-08-23 07:44:51',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'qr_QR_Palletedo_not_delete_c' => 
    array (
      'id' => 'qr_QR_Palletedo_not_delete_c',
      'name' => 'do_not_delete_c',
      'label' => 'LBL_DO_NOT_DELETE',
      'comments' => '',
      'help' => '',
      'module' => 'qr_QR_Pallete',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-10-04 12:05:43',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'qr_QR_Palletedriver_name_c' => 
    array (
      'id' => 'qr_QR_Palletedriver_name_c',
      'name' => 'driver_name_c',
      'label' => 'LBL_DRIVER_NAME',
      'comments' => '',
      'help' => '',
      'module' => 'qr_QR_Pallete',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-09-24 08:46:51',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'qr_QR_Palletefarm_c' => 
    array (
      'id' => 'qr_QR_Palletefarm_c',
      'name' => 'farm_c',
      'label' => 'LBL_FARM',
      'comments' => '',
      'help' => '',
      'module' => 'qr_QR_Pallete',
      'type' => 'enum',
      'max_size' => '100',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-09-19 08:12:00',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'farm_list',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'qr_QR_Palleteinc_c' => 
    array (
      'id' => 'qr_QR_Palleteinc_c',
      'name' => 'inc_c',
      'label' => 'LBL_INC',
      'comments' => '',
      'help' => '',
      'module' => 'qr_QR_Pallete',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-08-31 10:53:03',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'qr_QR_Palleteorganic_box_28_c' => 
    array (
      'id' => 'qr_QR_Palleteorganic_box_28_c',
      'name' => 'organic_box_28_c',
      'label' => 'LBL_ORGANIC_BOX_28',
      'comments' => '',
      'help' => '',
      'module' => 'qr_QR_Pallete',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-08-23 06:29:48',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'qr_QR_Palleteorganic_box_32_c' => 
    array (
      'id' => 'qr_QR_Palleteorganic_box_32_c',
      'name' => 'organic_box_32_c',
      'label' => 'LBL_ORGANIC_BOX_32',
      'comments' => '',
      'help' => '',
      'module' => 'qr_QR_Pallete',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-08-23 06:30:01',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'qr_QR_Palleteorganic_box_36_c' => 
    array (
      'id' => 'qr_QR_Palleteorganic_box_36_c',
      'name' => 'organic_box_36_c',
      'label' => 'LBL_ORGANIC_BOX_36',
      'comments' => '',
      'help' => '',
      'module' => 'qr_QR_Pallete',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-08-23 06:31:08',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'qr_QR_Palleteorganic_box_40_c' => 
    array (
      'id' => 'qr_QR_Palleteorganic_box_40_c',
      'name' => 'organic_box_40_c',
      'label' => 'LBL_ORGANIC_BOX_40',
      'comments' => '',
      'help' => '',
      'module' => 'qr_QR_Pallete',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-08-23 06:32:25',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'qr_QR_Palleteorganic_box_48_c' => 
    array (
      'id' => 'qr_QR_Palleteorganic_box_48_c',
      'name' => 'organic_box_48_c',
      'label' => 'LBL_ORGANIC_BOX_48',
      'comments' => '',
      'help' => '',
      'module' => 'qr_QR_Pallete',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-08-23 07:10:24',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'qr_QR_Palleteorganic_box_60_c' => 
    array (
      'id' => 'qr_QR_Palleteorganic_box_60_c',
      'name' => 'organic_box_60_c',
      'label' => 'LBL_ORGANIC_BOX_60',
      'comments' => '',
      'help' => '',
      'module' => 'qr_QR_Pallete',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-08-23 07:11:05',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'qr_QR_Palleteorganic_box_70_c' => 
    array (
      'id' => 'qr_QR_Palleteorganic_box_70_c',
      'name' => 'organic_box_70_c',
      'label' => 'LBL_ORGANIC_BOX_70',
      'comments' => '',
      'help' => '',
      'module' => 'qr_QR_Pallete',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-08-23 07:26:34',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'qr_QR_Palleteorganic_box_84_c' => 
    array (
      'id' => 'qr_QR_Palleteorganic_box_84_c',
      'name' => 'organic_box_84_c',
      'label' => 'LBL_ORGANIC_BOX_84',
      'comments' => '',
      'help' => '',
      'module' => 'qr_QR_Pallete',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-08-23 07:26:55',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'qr_QR_Palleteorganic_total_c' => 
    array (
      'id' => 'qr_QR_Palleteorganic_total_c',
      'name' => 'organic_total_c',
      'label' => 'LBL_ORGANIC_TOTAL',
      'comments' => '',
      'help' => '',
      'module' => 'qr_QR_Pallete',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-08-23 07:43:55',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'qr_QR_Palleteqr_image_c' => 
    array (
      'id' => 'qr_QR_Palleteqr_image_c',
      'name' => 'qr_image_c',
      'label' => 'LBL_QR_IMAGE',
      'comments' => '',
      'help' => '',
      'module' => 'qr_QR_Pallete',
      'type' => 'image',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2018-08-24 07:10:30',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '120',
      'ext3' => '',
      'ext4' => '',
    ),
    'qr_QR_Palletestatus_c' => 
    array (
      'id' => 'qr_QR_Palletestatus_c',
      'name' => 'status_c',
      'label' => 'LBL_STATUS',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'qr_QR_Pallete',
      'type' => 'enum',
      'max_size' => '100',
      'require_option' => '0',
      'default_value' => 'Draft',
      'date_modified' => '2018-09-24 08:50:42',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'status_list',
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'qr_QR_Palletetotal_boxes_c' => 
    array (
      'id' => 'qr_QR_Palletetotal_boxes_c',
      'name' => 'total_boxes_c',
      'label' => 'LBL_TOTAL_BOXES',
      'comments' => '',
      'help' => '',
      'module' => 'qr_QR_Pallete',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2018-08-23 08:01:24',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'qr_QR_Palletevehicle_number_c' => 
    array (
      'id' => 'qr_QR_Palletevehicle_number_c',
      'name' => 'vehicle_number_c',
      'label' => 'LBL_VEHICLE_NUMBER',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'qr_QR_Pallete',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2018-10-26 18:03:33',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
  ),
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/qr_QR_Boxes/metadata/detailviewdefs.php',
      'to' => 'custom/modules/qr_QR_Boxes/metadata/detailviewdefs.php',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/qr_QR_Boxes/metadata/detailviewdefs.php',
      'to' => 'custom/working/modules/qr_QR_Boxes/metadata/detailviewdefs.php',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/qr_QR_Boxes/metadata/editviewdefs.php',
      'to' => 'custom/modules/qr_QR_Boxes/metadata/editviewdefs.php',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/modules/qr_QR_Boxes/metadata/editviewdefs.php',
      'to' => 'custom/working/modules/qr_QR_Boxes/metadata/editviewdefs.php',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/modules/qr_QR_Boxes/metadata/listviewdefs.php',
      'to' => 'custom/modules/qr_QR_Boxes/metadata/listviewdefs.php',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/modules/qr_QR_Boxes/metadata/quickcreatedefs.php',
      'to' => 'custom/modules/qr_QR_Boxes/metadata/quickcreatedefs.php',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/modules/qr_QR_Boxes/metadata/quickcreatedefs.php',
      'to' => 'custom/working/modules/qr_QR_Boxes/metadata/quickcreatedefs.php',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/modules/qr_QR_Pallete/metadata/detailviewdefs.php',
      'to' => 'custom/modules/qr_QR_Pallete/metadata/detailviewdefs.php',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/modules/qr_QR_Pallete/metadata/detailviewdefs.php',
      'to' => 'custom/working/modules/qr_QR_Pallete/metadata/detailviewdefs.php',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/modules/qr_QR_Pallete/metadata/editviewdefs.php',
      'to' => 'custom/modules/qr_QR_Pallete/metadata/editviewdefs.php',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/modules/qr_QR_Pallete/metadata/editviewdefs.php',
      'to' => 'custom/working/modules/qr_QR_Pallete/metadata/editviewdefs.php',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/modules/qr_QR_Pallete/metadata/listviewdefs.php',
      'to' => 'custom/modules/qr_QR_Pallete/metadata/listviewdefs.php',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/modules/qr_QR_Pallete/metadata/popupdefs.php',
      'to' => 'custom/modules/qr_QR_Pallete/metadata/popupdefs.php',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/modules/qr_QR_Pallete/metadata/popupdefs.php',
      'to' => 'custom/working/modules/qr_QR_Pallete/metadata/popupdefs.php',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/modules/qr_QR_Pallete/metadata/quickcreatedefs.php',
      'to' => 'custom/modules/qr_QR_Pallete/metadata/quickcreatedefs.php',
    ),
    15 => 
    array (
      'from' => '<basepath>/SugarModules/modules/qr_QR_Pallete/metadata/quickcreatedefs.php',
      'to' => 'custom/working/modules/qr_QR_Pallete/metadata/quickcreatedefs.php',
    ),
    16 => 
    array (
      'from' => '<basepath>/Extension/modules/relationships/relationships/qr_qr_pallete_qr_qr_boxes_1MetaData.php',
      'to' => 'custom/Extension/modules/relationships/relationships/qr_qr_pallete_qr_qr_boxes_1MetaData.php',
    ),
    17 => 
    array (
      'from' => '<basepath>/Extension/modules/relationships/vardefs/qr_qr_pallete_qr_qr_boxes_1_qr_QR_Pallete.php',
      'to' => 'custom/Extension/modules/relationships/vardefs/qr_qr_pallete_qr_qr_boxes_1_qr_QR_Pallete.php',
    ),
    18 => 
    array (
      'from' => '<basepath>/Extension/modules/relationships/vardefs/qr_qr_pallete_qr_qr_boxes_1_qr_QR_Boxes.php',
      'to' => 'custom/Extension/modules/relationships/vardefs/qr_qr_pallete_qr_qr_boxes_1_qr_QR_Boxes.php',
    ),
    19 => 
    array (
      'from' => '<basepath>/Extension/modules/relationships/layoutdefs/qr_qr_pallete_qr_qr_boxes_1_qr_QR_Pallete.php',
      'to' => 'custom/Extension/modules/relationships/layoutdefs/qr_qr_pallete_qr_qr_boxes_1_qr_QR_Pallete.php',
    ),
    20 => 
    array (
      'from' => '<basepath>/Extension/modules/qr_QR_Boxes/Ext/Vardefs/sugarfield_truck_info_c.php',
      'to' => 'custom/Extension/modules/qr_QR_Boxes/Ext/Vardefs/sugarfield_truck_info_c.php',
    ),
    21 => 
    array (
      'from' => '<basepath>/Extension/modules/qr_QR_Boxes/Ext/Vardefs/sugarfield_product_category_c.php',
      'to' => 'custom/Extension/modules/qr_QR_Boxes/Ext/Vardefs/sugarfield_product_category_c.php',
    ),
    22 => 
    array (
      'from' => '<basepath>/Extension/modules/qr_QR_Boxes/Ext/Vardefs/sugarfield_qr_boxes_id_c.php',
      'to' => 'custom/Extension/modules/qr_QR_Boxes/Ext/Vardefs/sugarfield_qr_boxes_id_c.php',
    ),
    23 => 
    array (
      'from' => '<basepath>/Extension/modules/qr_QR_Boxes/Ext/Vardefs/sugarfield_product_name_c.php',
      'to' => 'custom/Extension/modules/qr_QR_Boxes/Ext/Vardefs/sugarfield_product_name_c.php',
    ),
    24 => 
    array (
      'from' => '<basepath>/Extension/modules/qr_QR_Boxes/Ext/Vardefs/sugarfield_name.php',
      'to' => 'custom/Extension/modules/qr_QR_Boxes/Ext/Vardefs/sugarfield_name.php',
    ),
    25 => 
    array (
      'from' => '<basepath>/Extension/modules/qr_QR_Boxes/Ext/Vardefs/sugarfield_qr_image_c.php',
      'to' => 'custom/Extension/modules/qr_QR_Boxes/Ext/Vardefs/sugarfield_qr_image_c.php',
    ),
    26 => 
    array (
      'from' => '<basepath>/Extension/modules/qr_QR_Boxes/Ext/Vardefs/sugarfield_no_of_boxes_c.php',
      'to' => 'custom/Extension/modules/qr_QR_Boxes/Ext/Vardefs/sugarfield_no_of_boxes_c.php',
    ),
    27 => 
    array (
      'from' => '<basepath>/Extension/modules/qr_QR_Boxes/Ext/Vardefs/qr_qr_pallete_qr_qr_boxes_1_qr_QR_Boxes.php',
      'to' => 'custom/Extension/modules/qr_QR_Boxes/Ext/Vardefs/qr_qr_pallete_qr_qr_boxes_1_qr_QR_Boxes.php',
    ),
    28 => 
    array (
      'from' => '<basepath>/Extension/modules/qr_QR_Boxes/Ext/Language/en_us.customqr_qr_pallete_qr_qr_boxes_1.php',
      'to' => 'custom/Extension/modules/qr_QR_Boxes/Ext/Language/en_us.customqr_qr_pallete_qr_qr_boxes_1.php',
    ),
    29 => 
    array (
      'from' => '<basepath>/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_class2_box_84_c.php',
      'to' => 'custom/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_class2_box_84_c.php',
    ),
    30 => 
    array (
      'from' => '<basepath>/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_organic_box_28_c.php',
      'to' => 'custom/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_organic_box_28_c.php',
    ),
    31 => 
    array (
      'from' => '<basepath>/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_class1_box_28.php',
      'to' => 'custom/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_class1_box_28.php',
    ),
    32 => 
    array (
      'from' => '<basepath>/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_class2_total_c.php',
      'to' => 'custom/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_class2_total_c.php',
    ),
    33 => 
    array (
      'from' => '<basepath>/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_organic_box_40_c.php',
      'to' => 'custom/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_organic_box_40_c.php',
    ),
    34 => 
    array (
      'from' => '<basepath>/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_vehicle_number_c.php',
      'to' => 'custom/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_vehicle_number_c.php',
    ),
    35 => 
    array (
      'from' => '<basepath>/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_organic_box_84_c.php',
      'to' => 'custom/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_organic_box_84_c.php',
    ),
    36 => 
    array (
      'from' => '<basepath>/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_class2_box_32_c.php',
      'to' => 'custom/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_class2_box_32_c.php',
    ),
    37 => 
    array (
      'from' => '<basepath>/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_organic_box_32_c.php',
      'to' => 'custom/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_organic_box_32_c.php',
    ),
    38 => 
    array (
      'from' => '<basepath>/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_class1_total_c.php',
      'to' => 'custom/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_class1_total_c.php',
    ),
    39 => 
    array (
      'from' => '<basepath>/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_class2_box_70_c.php',
      'to' => 'custom/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_class2_box_70_c.php',
    ),
    40 => 
    array (
      'from' => '<basepath>/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_class1_box_70_c.php',
      'to' => 'custom/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_class1_box_70_c.php',
    ),
    41 => 
    array (
      'from' => '<basepath>/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_organic_total_c.php',
      'to' => 'custom/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_organic_total_c.php',
    ),
    42 => 
    array (
      'from' => '<basepath>/Extension/modules/qr_QR_Pallete/Ext/Vardefs/qr_qr_pallete_qr_qr_boxes_1_qr_QR_Pallete.php',
      'to' => 'custom/Extension/modules/qr_QR_Pallete/Ext/Vardefs/qr_qr_pallete_qr_qr_boxes_1_qr_QR_Pallete.php',
    ),
    43 => 
    array (
      'from' => '<basepath>/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_class1_box_32_c.php',
      'to' => 'custom/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_class1_box_32_c.php',
    ),
    44 => 
    array (
      'from' => '<basepath>/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_class2_box_60_c.php',
      'to' => 'custom/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_class2_box_60_c.php',
    ),
    45 => 
    array (
      'from' => '<basepath>/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_class1_box_28_c.php',
      'to' => 'custom/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_class1_box_28_c.php',
    ),
    46 => 
    array (
      'from' => '<basepath>/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_organic_box_60_c.php',
      'to' => 'custom/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_organic_box_60_c.php',
    ),
    47 => 
    array (
      'from' => '<basepath>/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_class2_box_28_c.php',
      'to' => 'custom/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_class2_box_28_c.php',
    ),
    48 => 
    array (
      'from' => '<basepath>/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_class2_box_36_c.php',
      'to' => 'custom/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_class2_box_36_c.php',
    ),
    49 => 
    array (
      'from' => '<basepath>/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_farm_c.php',
      'to' => 'custom/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_farm_c.php',
    ),
    50 => 
    array (
      'from' => '<basepath>/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_name.php',
      'to' => 'custom/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_name.php',
    ),
    51 => 
    array (
      'from' => '<basepath>/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_organic_box_48_c.php',
      'to' => 'custom/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_organic_box_48_c.php',
    ),
    52 => 
    array (
      'from' => '<basepath>/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_class1_box_40_c.php',
      'to' => 'custom/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_class1_box_40_c.php',
    ),
    53 => 
    array (
      'from' => '<basepath>/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_class1_box_36_c.php',
      'to' => 'custom/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_class1_box_36_c.php',
    ),
    54 => 
    array (
      'from' => '<basepath>/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_status_c.php',
      'to' => 'custom/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_status_c.php',
    ),
    55 => 
    array (
      'from' => '<basepath>/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_class1_box_48_c.php',
      'to' => 'custom/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_class1_box_48_c.php',
    ),
    56 => 
    array (
      'from' => '<basepath>/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_inc_c.php',
      'to' => 'custom/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_inc_c.php',
    ),
    57 => 
    array (
      'from' => '<basepath>/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_qr_image_c.php',
      'to' => 'custom/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_qr_image_c.php',
    ),
    58 => 
    array (
      'from' => '<basepath>/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_do_not_delete_c.php',
      'to' => 'custom/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_do_not_delete_c.php',
    ),
    59 => 
    array (
      'from' => '<basepath>/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_class2_box_40_c.php',
      'to' => 'custom/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_class2_box_40_c.php',
    ),
    60 => 
    array (
      'from' => '<basepath>/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_organic_box_70_c.php',
      'to' => 'custom/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_organic_box_70_c.php',
    ),
    61 => 
    array (
      'from' => '<basepath>/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_class2_box_48_c.php',
      'to' => 'custom/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_class2_box_48_c.php',
    ),
    62 => 
    array (
      'from' => '<basepath>/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_driver_name_c.php',
      'to' => 'custom/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_driver_name_c.php',
    ),
    63 => 
    array (
      'from' => '<basepath>/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_class1_box_60_c.php',
      'to' => 'custom/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_class1_box_60_c.php',
    ),
    64 => 
    array (
      'from' => '<basepath>/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_organic_box_36_c.php',
      'to' => 'custom/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_organic_box_36_c.php',
    ),
    65 => 
    array (
      'from' => '<basepath>/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_total_boxes_c.php',
      'to' => 'custom/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_total_boxes_c.php',
    ),
    66 => 
    array (
      'from' => '<basepath>/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_class1_box_84_c.php',
      'to' => 'custom/Extension/modules/qr_QR_Pallete/Ext/Vardefs/sugarfield_class1_box_84_c.php',
    ),
    67 => 
    array (
      'from' => '<basepath>/Extension/modules/qr_QR_Pallete/Ext/Language/en_us.customqr_qr_pallete_qr_qr_boxes_1.php',
      'to' => 'custom/Extension/modules/qr_QR_Pallete/Ext/Language/en_us.customqr_qr_pallete_qr_qr_boxes_1.php',
    ),
    68 => 
    array (
      'from' => '<basepath>/Extension/modules/qr_QR_Pallete/Ext/Layoutdefs/_overrideqr_QR_Pallete_subpanel_qr_qr_pallete_qr_qr_boxes_1.php',
      'to' => 'custom/Extension/modules/qr_QR_Pallete/Ext/Layoutdefs/_overrideqr_QR_Pallete_subpanel_qr_qr_pallete_qr_qr_boxes_1.php',
    ),
    69 => 
    array (
      'from' => '<basepath>/Extension/modules/qr_QR_Pallete/Ext/Layoutdefs/qr_qr_pallete_qr_qr_boxes_1_qr_QR_Pallete.php',
      'to' => 'custom/Extension/modules/qr_QR_Pallete/Ext/Layoutdefs/qr_qr_pallete_qr_qr_boxes_1_qr_QR_Pallete.php',
    ),
  ),
);